//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musical_Course.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Areas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Areas()
        {
            this.Advertisement = new HashSet<Advertisement>();
        }
    
        public int AreaId { get; set; }
        public string Town { get; set; }
        public string Location { get; set; }
        public string Company { get; set; }
        public int Representative { get; set; }
        public string SiteType { get; set; }
        public string SiteDescription { get; set; }
        public int Capacity { get; set; }
        public bool AvailabilityOfEquipment { get; set; }
        public string Chart { get; set; }
        public int PreliminaryCost { get; set; }
        public string DescriptionOfTheTermsOfCooperation { get; set; }
        public string RecommendedFocusOfTheGroup { get; set; }
        public byte[] Photo1 { get; set; }
        public byte[] Photo2 { get; set; }
        public byte[] Photo3 { get; set; }
        public byte[] Photo4 { get; set; }
        public byte[] Photo5 { get; set; }
        public byte[] Photo6 { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertisement> Advertisement { get; set; }
        public virtual Users Users { get; set; }
    }
}
