//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musical_Course.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Groups()
        {
            this.Advertisement = new HashSet<Advertisement>();
        }
    
        public int BandId { get; set; }
        public string Name { get; set; }
        public int Representative { get; set; }
        public bool AvailabilityOfEquipment { get; set; }
        public string DescriptionOfTheActivity { get; set; }
        public string DesiredSite { get; set; }
        public int RecommendedCostOfTheSite { get; set; }
        public string GroupDescription { get; set; }
        public string DescriptionOfTheTermsOfCooperation { get; set; }
        public byte[] Photo1 { get; set; }
        public byte[] Photo2 { get; set; }
        public byte[] Photo3 { get; set; }
        public byte[] Photo4 { get; set; }
        public byte[] Photo5 { get; set; }
        public byte[] Photo6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertisement> Advertisement { get; set; }
        public virtual Users Users { get; set; }
    }
}
